CREATE OR REPLACE TRIGGER EMERSON.TRG_AUD_ALUNO
BEFORE INSERT OR DELETE OR UPDATE
ON EMERSON.ALUNO
REFERENCING NEW AS NEW OLD AS OLD
BEGIN
IF TO_NUMBER(TO_CHAR(SYSDATE, 'hh24')) NOT BETWEEN 9 AND 18
THEN
raise_application_error(-20001,'Opera��o n�o pode ser executada fora do hor�rio de expediente.');
END IF;
END;
/



